channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::snakemake-minimal =5.4.5
  - bwa =0.7.17
  - snippy =3.2
  - trim-galore =0.6.5
  - phyml =3.3.20190909
# dependencies R:
# ggtree
# ape
# readxl

